version: '3.8'

services:
  # Core Network Services
  amf:
    build:
      context: ./amf
      dockerfile: Dockerfile
    container_name: openmvcore-amf
    ports:
      - "${AMF_PORT:-8081}:8081"
    networks:
      - openmvcore-net
    depends_on:
      - redis
      - nats

  smf:
    build:
      context: ./smf
      dockerfile: Dockerfile
    container_name: openmvcore-smf
    ports:
      - "${SMF_PORT:-8805}:8805"
      - "2123:2123"
    networks:
      - openmvcore-net
    depends_on:
      - redis
      - nats
      - upf
      - udm

  upf:
    build:
      context: ./upf
      dockerfile: Dockerfile
    container_name: openmvcore-upf
    ports:
      - "8805:8805"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - openmvcore-net
    depends_on:
      - redis
      - nats

  # Support Services
  bss:
    build:
      context: ./bss
      dockerfile: Dockerfile
    container_name: openmvcore-bss
    ports:
      - "${BSS_PORT:-8084}:8084"
    networks:
      - openmvcore-net
    depends_on:
      - redis
      - nats

  ocs:
    build:
      context: ./ocs
      dockerfile: Dockerfile
    container_name: openmvcore-ocs
    ports:
      - "${OCS_PORT:-8082}:8082"
    networks:
      - openmvcore-net
    depends_on:
      - redis
      - nats

  udm:
    build:
      context: ./udm
      dockerfile: Dockerfile
    container_name: openmvcore-udm
    ports:
      - "${UDM_PORT:-8083}:8083"
    networks:
      - openmvcore-net
    depends_on:
      - redis
      - nats

  # Infrastructure Services
  redis:
    image: redis:7-alpine
    container_name: openmvcore-redis
    ports:
      - "6379:6379"
    networks:
      - openmvcore-net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:13-alpine
    container_name: openmvcore-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=openmv
      - POSTGRES_PASSWORD=openmv
      - POSTGRES_DB=openmv
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openmvcore-net

  # Optional: NATS for service communication
  nats:
    image: nats:2.10.11-alpine
    container_name: openmvcore-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - openmvcore-net
    command: ["-js"]
    healthcheck:
      test: ["CMD", "nats-server", "--help"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
  postgres_data:

networks:
  openmvcore-net:
    driver: bridge 